Write programs in Python using NumPy library to do the following:
a. Compute the mean, standard deviation, and variance of a two-dimensional random integer array along the second axis.
b. Create a 2-dimensional array of size m x n integer elements, also print the shape, type, and data type of the array, and then reshape it into an n x m array, where n and m are user inputs given at the run time.
c. Test whether the elements of a given 1D array are zero, non-zero, and NaN. Record the indices of these elements in three separate arrays.
d. Create three random arrays of the same size: Array1, Array2, and Array3. Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1. Find the Covariance and Correlation of Array1 with Array4 and Array5 respectively.
e. Create two random arrays of the same size 10: Array1, and Array2. Find the sum of the first half of both the arrays and the product of the second half of both arrays.

In [62]:
import numpy as np
#e
Array1 = np.random.randint(0,10,size=10)
Array2 = np.random.randint(0,10,size=10)
sum_of_first_half = Array1[:5]+Array2[:5]
prod_of_second_half = Array1[5:]*Array2[5:]

#d
Array3 = np.random.randint(0,10,size=10)
Array4 = Array3 - Array2
Array5 = Array1*2
covar_of_arr1_with_arr4 = np.cov(Array1,Array4)
covar_of_arr1_with_arr5 = np.cov(Array1,Array5)
corr_of_arr1_with_arr4 = np.corrcoef(Array1, Array4)
corr_of_arr1_with_arr5 = np.corrcoef(Array1, Array5)

#c
oneDArr = np.array([2,3,0,np.nan,2,0,np.nan])
zero = np.where(oneDArr == 0)
non_zero = np.where(oneDArr > 0)
Nan = np.where(np.isnan(oneDArr))
# print(zero, non_zero,Nan)


#b.
m = 8
n = 3
arraymn = np.random.randint(0,100, size=(m*n)).reshape(m,n)
arraymn.reshape(n,m)

# a.
array_2d = np.random.randint(0, 10, size=(3, 4))
mean = np.mean(array_2d, axis=1)
std_dev = np.std(array_2d, axis=1)
variance = np.var(array_2d, axis=1)



24 (8, 3) int32 2
[[6 8 6 5]
 [8 2 8 2]
 [2 0 9 3]]
[6.25 5.   3.5 ]
[1.08972474 3.         3.35410197]
[ 1.1875  9.     11.25  ]
