rides.csv:
Drivers Active Per Hour,Riders Active Per Hour,Rides Completed
72,295,202
50,78,43
40,250,181
78,140,124
74,195,108
37,291,172
46,94,79
97,280,166
61,134,99
49,224,51
68,145,70
37,69,29
99,113,93
90,200,81
44,286,196
47,279,248
28,235,147
78,173,100
62,205,80


Create ndarrays using various ways.
Implement the following attributes/functions:
ndim, shape, type, T, transpose, reshape, swapaxes, astype.

Arithmetic with NumPy Arrays on 1d and 2d arrays.

Indexing and Slicing, Boolean Indexing on Numpy

In [39]:
import numpy as np

# 1d array using arange function.
s1 = np.arange(10)
print(s1)

#2d array using array function.
s2 = np.array([[4,3,2,2],[5,4,3,3]])
print(s2)

# 3d array using random function.
s3 = np.random.randint(0,10, size=[3,3,3])
print(s3)


[0 1 2 3 4 5 6 7 8 9]
[[4 3 2 2]
 [5 4 3 3]]
[[[7 9 5]
  [9 8 3]
  [1 7 0]]

 [[8 1 6]
  [0 9 6]
  [6 5 4]]

 [[5 5 7]
  [8 9 5]
  [7 9 1]]]


Implement the following attributes/functions:
ndim, shape, type, T, transpose, reshape, swapaxes, astype.

In [44]:
print(s1.ndim,s2.ndim, s3.ndim)
print(s1.shape,s2.shape,s3.shape)
print(s1.dtype,s2.dtype,s3.dtype)
ft = s2.T
print(ft)
ftranspose = s2.transpose()
print(ftranspose)
#both are basically the same but we provide custom axis with transpose, it comes useful in multi-dimentional arrays.
s2.size
s2
s2.reshape(2,2,2)
swappeds2 = np.swapaxes(s2, 0,1)
s2
print('dtype of s3 is',s3.dtype)
s3.astype(float)



1 2 3
(10,) (2, 4) (3, 3, 3)
int32 int32 int32
[[4 5]
 [3 4]
 [2 3]
 [2 3]]
[[4 5]
 [3 4]
 [2 3]
 [2 3]]
dtype of s3 is int32


array([[[7., 9., 5.],
        [9., 8., 3.],
        [1., 7., 0.]],

       [[8., 1., 6.],
        [0., 9., 6.],
        [6., 5., 4.]],

       [[5., 5., 7.],
        [8., 9., 5.],
        [7., 9., 1.]]])

Arithmetic with numpy arrays on 1d and 2d arrays.  

In [11]:
import numpy as np

arr1 = np.arange(11)
arr2 = np.arange(10,21)
print(arr1,arr2)
arr2 + arr1
arr1 * arr2
arr2 / arr1
arr1 // arr2

arr1 + 2


[ 0  1  2  3  4  5  6  7  8  9 10] [10 11 12 13 14 15 16 17 18 19 20]


C:\Users\kant\AppData\Local\Temp\ipykernel_7928\2137283669.py:8: RuntimeWarning: divide by zero encountered in divide
  arr2 / arr1


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Indexing and slicing, Boolean indexing on numpy

In [18]:
arr1[0]
arr2[5]
arr1[1:5] + arr2[1:5]
#boolean indexing for even numbers
Bindex = arr1 % 2 ==0
arr1[Bindex]

array([ 0,  2,  4,  6,  8, 10])

create series and data frame using different ways:
 2d ndarray 
 dict of arrays 
 lists 
 tupes 
 dict of series
 dict of dicts
 list of dicts or series

Use of indexing, index methods (append, difference, intersection, union, isin, delete, drop, insert, is_monotonic, is_unique, unique).
Reindexing, Selection, and Filtering, Selection with loc and iloc. Arthimetic and Data Alignment (add, radd, sub, rsub, dic, rdiv, floordiv, mul,rmul, pow, rpow)

In [36]:
import pandas as pd
data = pd.read_csv('./rides.csv')
#printing the first 5 rows and all columns of the data
print(f'This is data head\n {data.head()}\n')
#printing first 10 rows of the first column
first10 = data['Drivers Active Per Hour'].head(10)
print(first10)
#printing first two columns and 2 rows from each column
a = data.iloc[:2,:2]
print(a)
data.sort_values(by=['Riders Active Per Hour'])


This is data head
    Drivers Active Per Hour  Riders Active Per Hour  Rides Completed
0                       72                     295            202.0
1                       50                      78             43.0
2                       40                     250            181.0
3                       78                     140            124.0
4                       74                     195            108.0

0    72
1    50
2    40
3    78
4    74
5    37
6    46
7    97
8    61
9    49
Name: Drivers Active Per Hour, dtype: int64
   Drivers Active Per Hour  Riders Active Per Hour
0                       72                     295
1                       50                      78


Drivers Active Per Hour  Riders Active Per Hour  Rides Completed
80                         10                     230             96.0
326                        10                     155             56.0
1011                       10                     293             90.0
267                        10                     249            174.0
1046                       10                     221            111.0
...                       ...                     ...              ...
809                       100                     248            145.0
1076                      100                     259            233.0
696                       100                     147            110.0
210                       100                     204            113.0
937                       100                     224            126.0

[1099 rows x 3 columns]